# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.player_people_current_team import PlayerPeopleCurrentTeam  # noqa: E501
from openapi_client.rest import ApiException


class TestPlayerPeopleCurrentTeam(unittest.TestCase):
    """PlayerPeopleCurrentTeam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlayerPeopleCurrentTeam(self):
        """Test PlayerPeopleCurrentTeam"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.player_people_current_team.PlayerPeopleCurrentTeam()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
