# coding: utf-8

"""
    NHL API

    Documenting the publicly accessible portions of the NHL API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.team_next_game_schedule_teams_away_team import TeamNextGameScheduleTeamsAwayTeam  # noqa: E501
from openapi_client.rest import ApiException


class TestTeamNextGameScheduleTeamsAwayTeam(unittest.TestCase):
    """TeamNextGameScheduleTeamsAwayTeam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTeamNextGameScheduleTeamsAwayTeam(self):
        """Test TeamNextGameScheduleTeamsAwayTeam"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.team_next_game_schedule_teams_away_team.TeamNextGameScheduleTeamsAwayTeam()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
